apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-env
  {{- with .Values.cortex.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
data:
  CORTEX_ELASTICSEARCH_USERNAME: {{ .Values.cortex.index.username | quote }}
  {{- if and (.Values.elasticsearch.enabled) (eq (len .Values.cortex.index.hostnames) 0) }}
  es_hostname: {{ printf "%s-elasticsearch" .Release.Name | trunc 63 | quote }}
  {{- else }}
  es_hostname: {{ join "," .Values.cortex.index.hostnames | quote }}
  {{- end }}
  job_directory: {{ .Values.cortex.jobDirectory | quote }}
  kubernetes_job_pvc: {{ include "cortex.persistentVolumeClaimName" . | quote }}
